
# theme: jekyll-theme-merlot
# # permalink: /404.html
# url: "bilei121.github.io"
# baseurl: "tailieubkhn"



# # theme: jekyll-theme-merlot
# permalink: /404.html
# url: "bilei121.github.io"
# targeturl: "bilei121.github.io"
# baseurl: "tailieubkhn"

theme: jekyll-theme-slate
